pipeline{
    agent any
    tools{
        maven 'My-maven'
    }
    stages{
        stage('checkout'){
            steps{
                git branch: 'main',
                    url: 'https://github.com/chulliyan/Skillify-Jenkins-Project.git'
            }
        }
        stage('Build'){
            steps{
                sh 'mvn clean compile'
            }
        }
        stage('Test'){
            steps{
                sh 'mvn test'
            }
        }
        stage('SonarQube Analysis'){
            environment{
                scannerHome = tool 'sonartool'
            }
            steps{
                withSonarQubeEnv('mysonar'){
                    sh '''
                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=chulliyan_Skillify-Jenkins-Project \
                        -Dsonar.java.binaries=target/classes \
                        -Dsonar.organization=chulliyan \
                    '''
                }
            }
        }
        stage('Package'){
            steps{
                sh 'mvn package'
            }
        }
        stage('Archive Artifacts'){
            steps{
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }
    }
}
