pipeline{
    agent any
    tools{
        maven 'My-maven'
    }
    stages{
        stage('checkout'){
            steps{
                git branch: 'main',
                    url: 'https://github.com/chulliyan/Skillify-Jenkins-Project.git'
            }
        }
        stage('Build'){
            steps{
                sh 'mvn clean compile'
            }
        }
        stage('Test'){
            steps{
                sh 'mvn test'
            }
        }
        stage('Package'){
            steps{
                sh 'mvn package'
            }
        }
    }
}
